version: "3.8"
services:

  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy-static
    depends_on:
    - httpbin
    ports:
    - 10000:10000
    - 11000:11000
    - 9901:9901
    volumes:
      - /tmp:/tmp
    networks:
      -  mani

  httpbin:
    build:
      context: .
      dockerfile: Dockerfile-httpbin
    hostname: httpbin
    ports:
    - 9080:80    
    networks:
      -  mani


networks:
  mani: